import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./Provider/providers";
import HomeNavBar from "./components/HomeNavBar/HomeNavBar";

export const metadata: Metadata = {
  title: "EGO-bank - Bank Accounts, Mortgages, Loans and Savings",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" />
      </head>
      <body>
        <Providers>
          <HomeNavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
